### PR TITLE
[CUERipper] Add empty Release in any case

### PR DESCRIPTION
**Pull request by c72578**
So far, a blank entry was only added, if no metadata was found.

- Add a blank Release to the metadata selection drop-down list in any
  case. It can be used, if the metadata retrieved is not correct or
  undesired.

### CODE REVIEW

**Comment by c72578** [comment]
This PR is intended to address the following request for CUERipper:
> Provide a blank space (or Unknown Artist - Unknown Title) in the metadata selection drop-down list for when the metadata retrieved is not correct for the inserted media (this can happen with CD Singles for example when only freedb results are returned).
https://hydrogenaud.io/index.php?topic=118915.0

Here are some screenshots:

1. Behavior before, no blank entry
Add_Empty_Release_0_before_Metadata_search_Default

2. Screenshot of build from this PR, blank entry added to drop-down list
Add_Empty_Release_1_fixed_Metadata_search_Default

3. Screenshot of build from this PR, blank entry selected (Unknown Artist - Unknown Title)
Add_Empty_Release_1_fixed_Empty_Release_selected

**Comment by c72578** [comment]
A build for testing has been prepared using GitHub Actions:

[CUETools_2.2.0_2022-01-13_git_26b5c56.zip](https://github.com/gchudov/cuetools.net/files/7865962/CUETools_2.2.0_2022-01-13_git_26b5c56.zip)
`SHA256: 09587dad6f61ad47a197b86c02baddfb7734a98bd96d24ffbec43370182972e4`

**Comment by ha-korth** [comment]
I have a minor concern about still using the same icon local32 as the local metadata cache.  

If there is an entry in the local metadata cache, then the cache entry and the empty release have the same icon.

empty

Someone may think this is a duplicate of the empty release.

**Comment by c72578** [comment]
@ha-korth Thanks for testing and the feedback concerning the icon.

Here are two suggestions:
1. Uses the already available "album" icon from `imageListMetadataSource`
album_crop

2. Empty icon
empty_crop

**Comment by ha-korth** [comment]
I honestly like the empty space but there probably should be some type of icon.
The album icon works okay.
Or maybe a framed empty space. box

**Comment by c72578** [comment]
OK, here is an example with a framed empty space:
blank_crop

**Comment by ha-korth** [comment]
Better than the yellow. I didn't look for an open source white page icon similar to  the album icon. I leave the decision to you.

**Comment by c72578** [comment]
@ha-korth Thanks for checking again.
In the following screenshot, an icon based on an svg from `Fluent UI System Icons` (MIT license) [1] is used:
blank_fluentui_Page_crop

I will update the PR with it.

[1] https://github.com/microsoft/fluentui-system-icons/blob/master/assets/Page/SVG/ic_fluent_page_20_regular.svg

**Comment by c72578** [comment]
Here is an updated build with the separate icon for testing:

[CUETools_2.2.0_2022-01-15_git_9c6030b.zip](https://github.com/gchudov/cuetools.net/files/7874679/CUETools_2.2.0_2022-01-15_git_9c6030b.zip)
`SHA256: fa5a4fc1d5f064d7ef56795b6cf44d5913589de3d826b234177bba8a89e78747`

**Comment by ha-korth** [comment]
👍

**Pull request merged**
