### PR TITLE
Update MAC_SDK from 4.44 to 9.04

### LINKED ISSUE #158: [REQUEST] Codec Update - Monkeys Audio
Would be great if the MA codec could be updated. It's at v7.x now.

Current Version : 7.50

### PR DESCRIPTION
**Pull request by c72578**
This is a larger update of MAC_SDK to release 9.04.
- Original download location:
  https://monkeysaudio.com/files/MAC_904_SDK.zip
  SHA256:
  09cfebe79986a9b8249cff9c3fd79663692e8e23139903df541905a2ecf44c6a
- Several function return values and arguments are 64-bit now in
  MAC_SDK 9.04, e.g. in IO.h:
    `int64 GetPosition();`
    `int64 GetSize();`
  Use type `long` accordingly and remove casts, which are not required
  anymore.
- Update the CUETools specific MACLibDll.cpp and MACLibDll.h based on
  the upstream modifications to MACDll.cpp and MACDll.h, respectively.
- Update ThirdParty_MAC_SDK_CUETools.patch accordingly
- CUETools.Codecs.MACLib\AudioEncoder.cs:
  Remove duplicate `m_settings = settings;`
- Resolves #158

### CODE REVIEW

**Comment by Barough** [comment]
Looking forward to maybe a test build. ;)

**Comment by c72578** [comment]
Here is a first test build:
[CUETools_2.2.2_2023-01-25_git_634c866_MAC_SDK_9.04.zip](https://github.com/gchudov/cuetools.net/files/10503889/CUETools_2.2.2_2023-01-25_git_634c866_MAC_SDK_9.04.zip)
`SHA256: 0cf13aff05b51f2708ae2d45e1f824330defb8c519c76fe926b11dbc7f8caba0`

**Comment by Barough** [comment]
Working fine here. Tested converting a bunch of different lossless files into APE without any issues. Converted files plays fine on foobar2000

**Comment by c72578** [comment]
@Barough Thanks for testing the build and providing the feedback.

**Pull request merged**
