### PR TITLE
Eject after rip (#116), Mitigate undetected CD change (#115) , etc.

### PR DESCRIPTION
**Pull request by RDamman**
Changes for CUERipper: Add option Eject after rip (#116), Mitigate undetected CD change (#115), Add option Block Eject disc while Ripping, Fix Eject/Insert CD bug (#120).

### CODE REVIEW

**Comment by c72578** [comment]
Hi Roy,
thanks for your PR, which is much appreciated!

This PR contains three topics. Could you please split this PR into separate ones?

E.g.:
**PR 1:**
```
CUERipper: Add option Eject after rip

Short description.
- Resolves #116
```

**PR 2:**
```
CUERipper: Mitigate undetected CD change

Short description.
- Fixes #115
```

**PR 3:**
```
CUERipper: Fix Eject/Insert CD bug

Short description.
- Fixes #120
```

**Comment by c72578** [comment]
A build for testing has been prepared using GitHub Actions:
[CUETools_2.1.9_2021-09-24_git_996febf.zip](https://github.com/gchudov/cuetools.net/files/7227397/CUETools_2.1.9_2021-09-24_git_996febf.zip)

`SHA256: 0e1b885b3a111fb58723bfd47a93d64a3c018975625570eedadf21ed6edb4748`

**Comment by RDamman** [comment]
Hallo Wolfgang,

> 
> This PR contains three topics. Could you please split this PR into separate ones?
> 

Sorry for my late response. I am sadly not able to split the PR in 3 or 4 separate PRs because I have made the change in one commit.

CUERipper: Add option Eject after rip and block eject while ripping.
Short description.
- Resolves #116
- Default is true for "Eject after rip" and false for "Block eject while ripping".

CUERipper: Mitigate undetected CD change
Short description.
- Mitigates #115
- Problem is caused by that Windows does not notify always directly programs of a media eject. Especially for a second or third CD drive. Insertion is after that also not directly detected leaving CUERipper using the wrong meta data. Ejecting from CUERipper and calling "updatedrive" mitigates the problem: Now the change is detected and also new media is detected correctly. But when using the eject button on the drive itself, the problem persists. A final solution would probably be the implementation of a FileSystemWatcher (https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-5.0) and discard listening to the WM_DEVICECHANGE messages.

CUERipper: Fix Eject/Insert CD bug
Short description.
- Fixes #120
- Because of changes for "Eject after rip" option, a call is needed to updatedrive if this option is enabled. Because the metadata can change (by changing the disc) before pressing OK after rip, a call to updatedrive is always desired.

**Comment by c72578** [comment]
Hi Roy, thanks again for this PR.
I will commit some modifications in a separate PR, based on this one.
This PR here is from the master branch of your fork, which is not ideal (it is recommended to use a separate branch for each PR).

**Pull request closed without merging**
