### PR TITLE
Fix filename capitalization

### PR DESCRIPTION
**Pull request by ipaucek4680**
On Linux and other platforms using case-sensitive filesystems, wrong capitalization in filenames will cause the build process to fail.

### CODE REVIEW

**Comment by c72578** [comment]
@ipaucek4680 Thanks for this PR.
- The required renaming of the subdirectory: `CUETools.Codecs.FLAKE -> CUETools.Codecs.Flake` is also part of PR #52. Let's see, to get that one merged first.
- Thanks for finding and reporting the wrong spelling of:
`ImagePreview.designer.cs -> ImagePreview.Designer.cs` and `resources\accuraterip_16.bmp -> Resources\accuraterip_16.bmp`

**Comment by c72578** [comment]
@ipaucek4680, thanks for amending the commit, now that PR #52 has been merged.
Could you please commit the following, remaining rename of your original commit:
`git mv CUETools.Codecs.Flake/CUETools.Codecs.FLAKE.csproj CUETools.Codecs.Flake/CUETools.Codecs.Flake.csproj`

Thanks,
Wolfgang

**Comment by ipaucek4680** [comment]
Thanks for the heads-up. I have updated the commit to include the rename.

**Comment by c72578** [comment]
Thanks for your contribution.

**Pull request merged**
